export class CreateCustomerDto{
    mainCustomerId: number
    status: boolean
    name: string
    code: string
    type: string
    contactPerson: string
    contactNo: string
    stdCode: string
    email: string
    grade: string
    salesLeadId: number
    salesCode: string
    destinationPort: string
    finalDestination: string
    pieceWeightTolerance: string
    invoiceTolerance: string
    state: string
    gstIn: string
    aadhaarNumber: number
    pan: number
    country: string
    lookupSLID: string
    address: string
    deleted: boolean
    createdBy: number
    createdOn: Date
    updatedBy: number
    updatedOn: Date
}